# test for HPC workflow
# ansible playbook for openpbs

#collect info from everything
- hosts: all

#Apply Common Installation and Config
- hosts: all
  gather_facts: false
  roles:
    - pbs-common

# Apply pbs server config, start services
- hosts: headnodes
  gather_facts: false
  roles:
    - pbs-server

# Apply pbs MoM config, start services
- hosts: computenodes
  gather_facts: false
  roles:
    - pbs-mom