### Deploy kubernetes cluster
## kube-ansible github
---

#- hosts: etcds
#  roles:
#    - etcd

### config loadbalancer for kube apiserver #####
- hosts: control_master:control_slave
  roles:
    - lb-setup

#- hosts: all
#  roles:
#  #  - cluster-common
#    - packages-install

### kube init
- hosts: control_master
  roles:
    - cluster-init



