---

##  base configuration for cluster nodes

#### disable swap ####
- name: disable swap
  swapoff: {}

#### load br_netfilter module ####
- name: load br_netfilter module
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: 'br_netfilter'
    create: yes
    state: present

- name: add sysctl config for bridged traffic
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    state: present
    create: yes
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: reload sysctl config
  shell: sysctl --system




