#Playbook for installing Slurm on a cluster

#collect info from everything
- hosts: all

# Apply Common Installation and Config
- hosts: cluster
  gather_facts: false
  roles:
    - slurm-common

# Apply Manager Config, start services
- hosts: manager
  gather_facts: false
  roles:
    - slurm-manager

# Start SLURM workers
- hosts: compute
  gather_facts: false
  roles:
    - slurm-workers