---
#### create high available clusters with kubeadm ####
##https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/
##https://github.com/kubernetes/kubeadm/blob/master/docs/ha-considerations.md#options-for-software-load-balancing

####create load balancer for kube-apiserver ####
#### run as static pods #########

- name: create keepalived directory on nodes
  file:
    path: /etc/keepalived
    state: directory

- name: create haproxy directory on nodes
  file:
    path: /etc/haproxy
    state: directory

- name: haproxy config file
  template:
    src: haproxy.conf.j2
    dest: /etc/haproxy/haproxy.cfg

- name: copy haproxy manifests to nodes
  template:
    src: haproxy.yaml.j2
    dest: /etc/kubernetes/manifests/haproxy.yaml

- name: copy keepalived manifests to nodes
  template:
    src: keepalived.yaml.j2
    dest: /etc/kubernetes/manifests/keepalived.yaml



