---
#### create high available clusters with kubeadm ####
##https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/
##https://github.com/kubernetes/kubeadm/blob/master/docs/ha-considerations.md#options-for-software-load-balancing

####create load balancer for kube-apiserver ####
#### run as static pods #########




























