---
############
- name: install nginx and keepalived packages
  hosts: nginx
  tasks:
    - name: install keepalived
      yum:
        name: keepalived
        state: latest

    - name: copy nginx repo
      copy:
        src: /etc/yum.repos.d/nginx.repo
        dest: /etc/yum.repos.d/nginx.repo

    - name: install nginx
      yum:
        name: nginx
        state: latest

    - name: replace nginx bin file
      copy:
        src: /home/ansible/playbooks/nginx/files/nginx1222withsticky/nginx
        dest: /usr/sbin/nginx

###########################
- name: config keepalived conf file of master nginx server
  hosts: masternginx
  tasks:
    - name: copy keepalived file
      copy:
        src: /home/ansible/playbooks/nginx/files/keepalived_2vips_master.conf
        dest: /etc/keepalived/keepalived.conf

- name: config keepalived conf file of backup nginx server
  hosts: backupnginx
  tasks:
    - name: copy keepalived file
      copy:
        src: /home/ansible/playbooks/nginx/files/keepalived_2vips_backup.conf
        dest: /etc/keepalived/keepalived.conf

- name: modify keepalived conf file
  hosts: nginx
  vars_files:
    - /home/ansible/playbooks/nginx/group_vars/vips.yml
  tasks:
    - name: modify router id
      replace:
        path: /etc/keepalived/keepalived.conf
        regexp: 'nginxhost'
        replace: '{{ ansible_hostname }}'

    - name: modify vip keepalived conf file
      replace:
        path: /etc/keepalived/keepalived.conf
        regexp: 'nginxvip01'
        replace: '{{ vip01 }}'

    - name: modify vip keepalived conf file
      replace:
        path: /etc/keepalived/keepalived.conf
        regexp: 'nginxvip02'
        replace: '{{ vip02 }}'

#############################
- name: modify nginx.conf
  hosts: nginx
  tasks:
    - name: override nginx.conf
      copy: 
        src: /home/ansible/playbooks/nginx/files/nginx.conf
        dest: /etc/nginx/nginx.conf
        backup: yes
                                      

#############################
- name: start and enable keepalived 
  hosts: nginx
  tasks:
    - name: start and enable keepalived
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - nginx
        - keepalived


###############################
- name: modify system kernel and limits
  hosts: nginx
  vars_files:
    - /home/ansible/playbooks/nginx/group_vars/sys_limits.yml
  tasks:
    - name: modify kernel
      lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item }}"
        backup: yes
      with_items: "{{ kernelparas }}"
 
    - name: modify system limits
      lineinfile:
        path: /etc/security/limits.conf
        line: "{{ item }}"
        backup: yes
      with_items: "{{ limits }}"

    - name: modify limits.d default 
      replace:
        path: /etc/security/limits.d/20-nproc.conf
        regexp: '^\*'
        replace: '#*'
        backup: yes
